#!/usr/bin/env bash

commandAdd status cmdStatus

cmdStatusHelp() {
    cat <<EOF
   status          Displays each repository's status.
EOF
}


# Get a status of the project
cmdStatus() {
    projectForEach cmdStatusEach
}


# Called for each project.  Checks the commit status.
#
# $1 - Project identifier.
#
# Always returns true.  Can never fail.
cmdStatusEach() {
    local path statusResult

    path="$(getProjectConfig "$1" path)"

    if [[ -z "$path" ]]; then
        status "$1: No path set."

        return 0
    fi

    if [[ ! -d "$path" ]]; then
        status "$1: Not checked out."

        return 0
    fi

    statusResult=$(cd "$path" ; git status)

    if echo "$statusResult" | grep -q "^nothing to commit, working tree clean$"; then
        status "$1: clean"
    else
        status "$1: dirty"
        echo "$statusResult"
    fi
}
