#!/usr/bin/env bash

commandAdd status cmdStatus

cmdStatusHelp() {
    cat <<EOF
   status             Displays each repository's status. 
EOF
}


# Get a status of the project
cmdStatus() {
    projectForEach cmdStatusEach
}


# Called for each project.  Checks the commit status.
#
# $1 - Project identifier.
#
# Always returns true.  Can never fail.
cmdStatusEach() {
    local actualBranch desiredBranch path statusResult

    path="$(getProjectConfig "$1" path)"
    desiredBranch="$(getProjectConfig "$1" branch)"

    if [[ -z "$path" ]]; then
        status "$1: No path set."

        return 0
    fi

    if [[ ! -d "$path" ]]; then
        status "$1: Not checked out."

        return 0
    fi

    statusResult=$(cd "$path"; git status)

    # git 2.9 and 2.10:  nothing to commit, working tree clean
    # git 1.7:  nothing to commit, working directory clean
    if echo "$statusResult" | grep -q "^nothing to commit, working .* clean$"; then
        status "$1: clean"
    else
        status "$1: dirty"
        echo "$statusResult"
    fi

    if [[ -n "$desiredBranch" ]]; then
        actualBranch="$(cd "$path"; git branch | grep "^\\* " | cut -d " " -f 2-)"

        if [[ "$actualBranch" != "$desiredBranch" ]]; then
            echo "On branch '$actualBranch' instead of '$desiredBranch'"
        fi
    fi
}
