#!/usr/bin/env bash
# Adds a command to the list of available commands.  They are stored as
# separate global variables and the value is the name of the function to call.
#
# $1 - Name of command a user can type in.
# $2 - Function or command to call.
#
# Yes, this does use eval.  I'd be happy to accept pull requests that solve
# this problem.
#
# Returns nothing.
commandAdd() {
    eval "commandList_$1=$2"
}
