#!/usr/bin/env bash
# Gets config values for a project. Defaults to the "default" list if there is
# no setting.
#
# $1 - Project name.
# $2 - Config key.
#
# Writes out the value to stdout.
getProjectConfig() {
    local name

    name=$(ini-key-name "gg_manifest" "$1" "$2")

    if [[ -z "${!name-}" ]]; then
        name=$(ini-key-name "gg_manifest" "default" "$2")
    fi

    echo "${!name-}"
}
