#!/usr/bin/env bash
# Iterate over each defined project and call a command.
#
# $1 - The command to call.
#
# The command is called with the project name, as in
#
#   theCommandToCall "my-project"
#
# The command itself may determine the path and other factors based on the
# project name.
#
# Returns the number of commands that failed.  When there are no errors, this
# returns 0.
projectForEach() {
    local cmd jobs project

    jobs=()
    printf -v cmd "%q " "$@"

    # Do not redeclare gg_manifest
    # shellcheck disable=SC2154
    for project in "${gg_manifest[@]}"; do
        if [[ "$project" != "default" ]]; then
            jobs[${#jobs[@]}]="echo \"\$($cmd \"$project\" 2>&1)\""
        fi
    done

    if [[ "${#jobs[@]}" -gt 0 ]]; then
        parallelize "${jobs[@]}"
    fi
}
