#!/usr/bin/env bash
# List of project repositories.  Order matches `projectPaths`.
projectRepos=("" "")

# List of project paths.  Order matches `projectRepos`.
projectPaths=("$metaDir/gg-core" "$metaDir/manifest")

# Provide information regarding the location and source for a git repository.
#
# $1 - Repository URL used for cloning.
# $2 - Path where it should live.
project() {
    projectRepos[${#projectRepos[@]}]=$1
    projectPaths[${#projectPaths[@]}]=$2
}
