#!/usr/bin/env bash
# Iterate over each defined project and call a command.
#
# $1 - The command to call.
#
# The command is called with the path and source url, as in
#
#   theCommandToCall "some/path" "git@github.com:some/url"
#
# Stops at the first error and returns the error code.  When no errors are
# encountered, this returns 0.
projectForEach() {
    local path pathVarName project remote remoteVarName

    for project in "${gg_manifest[@]}"; do
        if [[ "$project" != "default" ]]; then
            "$1" "$project"
        fi
    done
}
